AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'task file'


Resources:
  ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Dev
      DefinitionUri: ./apigateway.yaml

  getIpaddress:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getIpaddressandtimezones
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./getjson.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::320189886616:role/lambda_api
